import { hashPassword } from './_core/auth.ts';
import type { DBState } from './db.ts';

export async function getDevelopmentSeed(): Promise<DBState> {
  const adminPassword = await hashPassword('admin123456');
  const ownerPassword = await hashPassword('bureau123456');

  return {
    users: [
      {
        id: 1,
        openId: null,
        name: 'مدير منصة مدار (تطوير)',
        email: 'admin@madar.sa',
        passwordHash: adminPassword,
        role: 'admin',
        emailVerifiedAt: new Date().toISOString(),
        deletedAt: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 2,
        openId: null,
        name: 'الشيخ عبدالرحمن التميمي (مكتب التوفيق - تطوير)',
        email: 'owner@altawfeeq.sa',
        passwordHash: ownerPassword,
        role: 'owner',
        emailVerifiedAt: new Date().toISOString(),
        deletedAt: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: 3,
        openId: null,
        name: 'عبدالله بن سعد المطيري (مستفيد - تطوير)',
        email: 'client@madar.sa',
        passwordHash: ownerPassword,
        role: 'user',
        emailVerifiedAt: new Date().toISOString(),
        deletedAt: null,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    sites: [
      {
        id: 1,
        userId: 2,
        subdomain: 'altawfeeq',
        customDomain: 'altawfeeq.sa',
        name: 'مكتب التوفيق للزواج الشرعي',
        tagline: 'بناء الأسر المسلمة على المودة والرحمة والسرية التامة وفق الكتاب والسنة',
        template: 'traditional',
        status: 'active',
        officePhone: '+966501234567',
        officeAddress: 'الرياض - حي الملز - طريق صلاح الدين الأيوبي - برج المودة، الدور الرابع',
        officeWorkingHours: 'السبت - الخميس: من ٩:٠٠ صباحاً حتى ٩:٠٠ مساءً',
        officeLicenseNumber: 'ترخيص وزارة العدل رقم: 441098/ز',
        officeYearsOfExperience: 14,
        officeAbout: 'تأسس مكتب التوفيق ليكون صرحاً آمناً للراغبين في الزواج الشرعي المعتمد، بفريق متخصص من الاستشاريين الأسريين والشرعيين نضمن لك السرية التامة ودقة التوافق القيمي والاجتماعي.',
        quranVerse: '﴿ وَمِنْ آيَاتِهِ أَنْ خَلَقَ لَكُم مِّنْ أَنفُسِكُمْ أَزْوَاجًا لِّتَسْكُنُوا إِلَيْهَا وَجَعَلَ بَيْنَكُم مَّوَدَّةً وَرَحْمَةً ﴾ [الروم: 21]',
        hadithText: 'قال رسول الله ﷺ: «إذا أتاكم من ترضون دينه وخلقه فزوجوه، إلا تفعلوا تكن فتنة في الأرض وفساد عريض»',
        successRate: 94,
        totalMarriages: 480,
        primaryColor: '#D4AF37',
        logoUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=300&q=80',
        coverUrl: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=1200&q=80',
        whatsappNumber: '+966501234567',
        emailContact: 'info@altawfeeq.sa',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    siteVersions: [
      {
        id: 1,
        siteId: 1,
        versionNumber: 1,
        configData: { template: 'traditional' },
        publishedAt: new Date().toISOString(),
      },
    ],
    siteVisits: [],
    analyticsDaily: [],
    messages: [],
    domains: [
      {
        id: 1,
        siteId: 1,
        domainName: 'altawfeeq.sa',
        status: 'verified',
        verifiedAt: new Date().toISOString(),
        createdAt: new Date().toISOString(),
      },
    ],
    mediaAssets: [],
    wallets: [
      {
        id: 1,
        userId: 2,
        balance: '450.00',
        currency: 'USD',
        updatedAt: new Date().toISOString(),
      },
    ],
    walletTransactions: [
      {
        id: 1,
        walletId: 1,
        amount: '500.00',
        type: 'deposit',
        description: 'شحن رصيد المحفظة عبر USDT (TRC-20)',
        referenceId: 'TX-982173',
        createdAt: new Date().toISOString(),
      },
      {
        id: 2,
        walletId: 1,
        amount: '-50.00',
        type: 'purchase',
        description: 'تفعيل حزمة التنبيهات والرسائل النصية VIP',
        referenceId: 'SUB-4412',
        createdAt: new Date().toISOString(),
      },
    ],
    walletDepositRequests: [],
    currencyRates: [
      { id: 1, code: 'SAR', nameAr: 'ريال سعودي', rateToUSD: '3.75', symbol: 'ر.س', updatedAt: new Date().toISOString() },
      { id: 2, code: 'AED', nameAr: 'درهم إماراتي', rateToUSD: '3.67', symbol: 'د.إ', updatedAt: new Date().toISOString() },
      { id: 3, code: 'KWD', nameAr: 'دينار كويتي', rateToUSD: '0.31', symbol: 'د.ك', updatedAt: new Date().toISOString() },
      { id: 4, code: 'EGP', nameAr: 'جنيه مصري', rateToUSD: '48.50', symbol: 'ج.م', updatedAt: new Date().toISOString() },
      { id: 5, code: 'USD', nameAr: 'دولار أمريكي', rateToUSD: '1.00', symbol: '$', updatedAt: new Date().toISOString() },
    ],
    currencyExchangeTransactions: [],
    purchaseRequests: [],
    sitePurchases: [
      {
        id: 1,
        siteId: 1,
        userId: 2,
        amountPaid: '299.00',
        currency: 'USD',
        purchasedAt: new Date().toISOString(),
        expiresAt: null,
        tier: 'lifetime',
      },
    ],
    paymentMethods: [
      {
        id: 1,
        code: 'bank_transfer',
        titleAr: 'تحويل بنكي رسمي',
        detailsAr: 'IBAN: SA0380000201827461947261 - باسم شركة مدار لتقنية المعلومات',
        isActive: true,
        instructions: 'يتم تأكيد التحويل المالي وتفعيل المحفظة بعد مراجعة الإيصال من الإدارة',
      },
    ],
    platformSettings: [
      { id: 1, keyName: 'lifetime_site_price', keyValue: '299.00', description: 'سعر شراء موقع المكتب مدى الحياة' },
      { id: 2, keyName: 'monthly_maintenance_fee', keyValue: '0.00', description: 'رسوم الصيانة الشهرية' },
      { id: 3, keyName: 'support_whatsapp', keyValue: '+966500000000', description: 'واتساب الدعم الفني للمنصة' },
      { id: 4, keyName: 'platform_name', keyValue: 'منصة مدار لمكاتب الزواج الشرعي', description: 'اسم المنصة الرسمي' },
    ],
    platformRevenue: [
      { id: 1, source: 'شراء موقع مكتب زواج', amount: '299.00', currency: 'USD', siteId: 1, userId: 2, recordedAt: new Date().toISOString() },
    ],
    notifications: [],
    auditLogs: [
      {
        id: 1,
        userId: 1,
        action: 'system_initialized',
        details: 'تم إطلاق بيئة التطوير التجريبية لمنصة مدار',
        ipAddress: '127.0.0.1',
        createdAt: new Date().toISOString(),
      },
    ],
    marriageRequests: [
      {
        id: 1,
        siteId: 1,
        userId: 3,
        fullName: 'عبدالله بن سعد المطيري',
        gender: 'male',
        age: 31,
        maritalStatus: 'single',
        city: 'الرياض',
        nationality: 'سعودي',
        education: 'ماجستير هندسة برمجيات',
        job: 'مهندس نظم في شركة حكومية كبرى',
        height: 178,
        weight: 75,
        religiousCommitment: 'محافظ ومواظب على الصلوات في المسجد',
        financialStatus: 'ممتاز ولله الحمد، يملك سكناً مستقلاً',
        partnerRequirements: 'أبحث عن فتاة ذات خلق ودين أصيل، جامعية، عمرها بين 22 و28 سنة، هادئة الطبع، تقدّر الحياة الزوجية والاستقرار الأسري.',
        phone: '+966501112233',
        email: 'client@madar.sa',
        preferredContact: 'whatsapp',
        guardianPhone: '+966509998877',
        notes: 'مستعد لإتمام الزواج خلال ٤ إلى ٦ أشهر بمشيئة الله.',
        photoUrl: '',
        termsAccepted: true,
        status: 'reviewed',
        internalNotes: 'تم التحقق من بيانات العمل والسمعة، شاب خلوق ومناسب للمطابقة.',
        matchedWithRequestId: null,
        createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    successStories: [],
    articles: [],
    packages: [
      {
        id: 1,
        siteId: 1,
        name: 'الباقة الأساسية',
        description: 'خدمة البحث والمطابقة المبدئية لراغبي الزواج الجادين',
        price: '450.00',
        currency: 'SAR',
        features: ['تسجيل وتدقيق الطلب', '3 ترشيحات متوافقة', 'تنسيق أولي مع الولي'],
        isPopular: false,
        sortOrder: 1,
        createdAt: new Date().toISOString(),
      },
    ],
    faqs: [
      {
        id: 1,
        siteId: 1,
        question: 'كيف تضمنون سرية بيانات المتقدمين؟',
        answer: 'بياناتكم أمانة شرعية ونظامية، لا تظهر أرقام التواصل ولا الهويات إلا بعد موافقة الطرفين والتنسيق المباشر مع ولي الأمر.',
        sortOrder: 1,
        createdAt: new Date().toISOString(),
      },
    ],
  };
}
